version: '3.8'

services:
  database:
    image: postgres:15
    container_name: postgres_spleenafx
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: spleenafx
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
